version: "2.3"
services:
    redis:
        image: redis
        container_name: redis
        restart: always
        networks:
            - my-network
    selenium:
        image: selenium/standalone-chrome:3.141.59-20200326
        container_name: selenium
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        networks:
            - my-network
        ports:
            - 4444:4444
    db:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        restart: always
        networks:
            - my-network
        ports:
            - 5432:5432
        volumes:
            - ./test_volume:/var/lib/postgresql/data
    webapp:
        build:
            context: .
            target: webapp
        container_name: poor_trip
        restart: always
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/
        networks:
            my-network:
                aliases:
                    - flask-app
        ports:
            - 8080:5000
        links:
            - db
            - redis
            - selenium
        depends_on:
            - db
            - redis
            - selenium
    celery:
        build:
            context: .
            target: celery
        container_name: celery
        restart: always
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/
            - FLASK_APP=webapp
        networks:
            - my-network
        links:
            - redis
        depends_on:
            - redis
            - webapp
            - db
    nginx:
        image: nginx:1.13.7
        container_name: nginx
        restart: always
        depends_on: 
            - webapp
        networks:
            - my-network
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
networks:
    my-network:
