version: "2"
services:
    redis:
        image: redis
        container_name: redis
    # selenium:
    #     image: selenium/standalone-chrome:3.141.59-20200326
    #     volumes:
    #         - /dev/shm:/dev/shm
    #     ports:
    #         - 4444:4444
    db:
        environment: 
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        image: postgres
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./test_volume:/var/lib/postgresql/data
                
    webapp:
        build: .
        container_name: poor_trip
        # command: ["./import.sh"]
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/
            # - CELERY_RESULT_BACKEND=redis://redis:6379
            - FLASK_APP=webapp
            - FLASK_ENV=development
            - FLASK_APP_PORT=5000
        ports:
            - 5000:5000
        links:
            - redis
            - db
        #     # - selenium
        depends_on:
            - redis
            - db
            # - selenium