version: "2.3"
services:
    redis:
        image: redis
        container_name: redis
    # selenium:
    #     image: selenium/standalone-chrome:3.141.59-20200326
    #     volumes:
    #         - /dev/shm:/dev/shm
    #     ports:
    #         - 4444:4444
    db:
        image: postgres
        container_name: postgres
        environment: 
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./test_volume:/var/lib/postgresql/data
    webapp:
        build:
            context: .
            target: webapp
        container_name: poor_trip
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/
            # - CELERY_RESULT_BACKEND=redis://redis:6379
            - FLASK_APP=webapp
            - FLASK_ENV=development
            - FLASK_APP_PORT=5000
        ports:
            - 5000:5000
        links:
            - db
            - redis
            # - selenium
        depends_on:
            - db
            - redis
            # - selenium
    celery:
        build:
            context: .
            target: celery
        container_name: celery
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/
            - FLASK_APP=webapp
        links:
            - redis
        depends_on:
            - redis
            - webapp
            - db
    