"""first migrate

Revision ID: 10f55af1f1a0
Revises: 
Create Date: 2020-03-31 23:13:24.280247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f55af1f1a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Hotels')
    op.drop_table('City')
    op.drop_table('AvgPricesReviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AvgPricesReviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.VARCHAR(), nullable=True),
    sa.Column('avg_reviews', sa.INTEGER(), nullable=True),
    sa.Column('avg_week_price', sa.INTEGER(), nullable=True),
    sa.Column('avg_day_price', sa.INTEGER(), nullable=True),
    sa.Column('parsing_date', sa.VARCHAR(), nullable=True),
    sa.Column('week_number', sa.INTEGER(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('City',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('eng_part_of_the_world', sa.VARCHAR(), nullable=True),
    sa.Column('ru_part_of_the_world', sa.VARCHAR(), nullable=True),
    sa.Column('eng_name', sa.VARCHAR(), nullable=True),
    sa.Column('ru_name', sa.VARCHAR(), nullable=True),
    sa.Column('eng_country', sa.VARCHAR(), nullable=True),
    sa.Column('ru_country', sa.VARCHAR(), nullable=True),
    sa.Column('city_img', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eng_name'),
    sa.UniqueConstraint('ru_name')
    )
    op.create_table('Hotels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('week_price', sa.INTEGER(), nullable=True),
    sa.Column('checkin_date', sa.VARCHAR(), nullable=True),
    sa.Column('checkout_date', sa.VARCHAR(), nullable=True),
    sa.Column('hotel_link', sa.VARCHAR(), nullable=True),
    sa.Column('parsing_date', sa.VARCHAR(), nullable=True),
    sa.Column('week_number', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('reviews', sa.INTEGER(), nullable=True),
    sa.Column('stars', sa.VARCHAR(), nullable=True),
    sa.Column('distance_from_center', sa.VARCHAR(), nullable=True),
    sa.Column('img_url', sa.VARCHAR(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
