"""empty message

Revision ID: 4c74bae6c41c
Revises: 9fb40a7c4b39
Create Date: 2020-04-17 21:31:57.186754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c74bae6c41c'
down_revision = '9fb40a7c4b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('parsing_date', sa.String(), nullable=True))
    op.drop_column('ticket', 'arriving_date')
    op.drop_column('ticket', 'departure_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('departure_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ticket', sa.Column('arriving_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ticket', 'parsing_date')
    # ### end Alembic commands ###
