"""empty message

Revision ID: 532269f7fd6c
Revises: 
Create Date: 2020-04-01 19:22:59.059772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532269f7fd6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('City',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_column', sa.Integer(), nullable=True),
    sa.Column('eng_part_of_the_world', sa.String(), nullable=True),
    sa.Column('ru_part_of_the_world', sa.String(), nullable=True),
    sa.Column('eng_name', sa.String(), nullable=True),
    sa.Column('ru_name', sa.String(), nullable=True),
    sa.Column('eng_country', sa.String(), nullable=True),
    sa.Column('ru_country', sa.String(), nullable=True),
    sa.Column('city_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eng_name'),
    sa.UniqueConstraint('ru_name')
    )
    op.create_table('AvgPricesReviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('avg_reviews', sa.Integer(), nullable=True),
    sa.Column('avg_week_price', sa.Integer(), nullable=True),
    sa.Column('avg_day_price', sa.Integer(), nullable=True),
    sa.Column('parsing_date', sa.String(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('week_price', sa.Integer(), nullable=True),
    sa.Column('checkin_date', sa.String(), nullable=True),
    sa.Column('checkout_date', sa.String(), nullable=True),
    sa.Column('hotel_link', sa.String(), nullable=True),
    sa.Column('parsing_date', sa.String(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('stars', sa.String(), nullable=True),
    sa.Column('distance_from_center', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Hotels')
    op.drop_table('AvgPricesReviews')
    op.drop_table('City')
    # ### end Alembic commands ###
