"""empty message

Revision ID: 60a30438db55
Revises: 
Create Date: 2020-04-12 18:35:44.117193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a30438db55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Airport_Ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('airport_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airport_id'),
    sa.UniqueConstraint('city')
    )
    op.create_table('City',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eng_part_of_the_world', sa.String(), nullable=True),
    sa.Column('ru_part_of_the_world', sa.String(), nullable=True),
    sa.Column('eng_name', sa.String(), nullable=True),
    sa.Column('ru_name', sa.String(), nullable=True),
    sa.Column('eng_country', sa.String(), nullable=True),
    sa.Column('ru_country', sa.String(), nullable=True),
    sa.Column('city_img', sa.String(), nullable=True),
    sa.Column('inexpensive_meal_price', sa.Float(), nullable=True),
    sa.Column('restaurant_2_persons', sa.Integer(), nullable=True),
    sa.Column('water_033', sa.Integer(), nullable=True),
    sa.Column('one_way_ticket', sa.Integer(), nullable=True),
    sa.Column('internet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eng_name'),
    sa.UniqueConstraint('ru_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('Attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('AvgPricesReviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('avg_reviews', sa.Integer(), nullable=True),
    sa.Column('avg_week_price', sa.Integer(), nullable=True),
    sa.Column('avg_day_price', sa.Integer(), nullable=True),
    sa.Column('parsing_date', sa.String(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('week_price', sa.Integer(), nullable=True),
    sa.Column('avg_day_price', sa.Integer(), nullable=True),
    sa.Column('checkin_date', sa.String(), nullable=True),
    sa.Column('checkout_date', sa.String(), nullable=True),
    sa.Column('hotel_link', sa.String(), nullable=True),
    sa.Column('parsing_date', sa.String(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('stars', sa.String(), nullable=True),
    sa.Column('distance_from_center', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Hotels')
    op.drop_table('AvgPricesReviews')
    op.drop_table('Attractions')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_table('City')
    op.drop_table('Airport_Ids')
    # ### end Alembic commands ###
