"""empty message

Revision ID: 7af64d1b164e
Revises: 4c74bae6c41c
Create Date: 2020-04-28 16:24:02.235540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7af64d1b164e'
down_revision = '4c74bae6c41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('living_prices', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('city', 'one_way_ticket')
    op.drop_column('city', 'inexpensive_meal_price')
    op.drop_column('city', 'restaurant_2_persons')
    op.drop_column('city', 'water_033')
    op.drop_column('city', 'internet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('internet', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('city', sa.Column('water_033', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('city', sa.Column('restaurant_2_persons', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('city', sa.Column('inexpensive_meal_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('city', sa.Column('one_way_ticket', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('city', 'living_prices')
    # ### end Alembic commands ###
