"""added Ticket table

Revision ID: 9fb40a7c4b39
Revises: ec88e206f366
Create Date: 2020-04-17 01:00:55.295069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fb40a7c4b39'
down_revision = 'ec88e206f366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_outbound_id', sa.Integer(), nullable=True),
    sa.Column('city_inbound_id', sa.Integer(), nullable=True),
    sa.Column('outbound_date', sa.String(), nullable=True),
    sa.Column('inbound_date', sa.String(), nullable=True),
    sa.Column('departure_date', sa.String(), nullable=True),
    sa.Column('arriving_date', sa.String(), nullable=True),
    sa.Column('price', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['city_inbound_id'], ['city.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_outbound_id'], ['airport_id.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_city_inbound_id'), 'ticket', ['city_inbound_id'], unique=False)
    op.create_index(op.f('ix_ticket_city_outbound_id'), 'ticket', ['city_outbound_id'], unique=False)
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('json_test', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.drop_index(op.f('ix_ticket_city_outbound_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_city_inbound_id'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
